version: '3'

services:
  database:
    image: 'mysql/mysql-server:5.7'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=musala
      - MYSQL_USER=musalauser
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/gateways.sql:/docker-entrypoint-initdb.d/2.sql
      - ./database/devices.sql:/docker-entrypoint-initdb.d/3.sql
      - ./database/seq.sql:/docker-entrypoint-initdb.d/4.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 20s
      retries: 10
    restart: always
    networks:
      - backend


  back-server:
    build: ./backend/
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database
    restart: always
    networks:
      - backend
      - frontend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/musala
      SPRING_DATASOURCE_USERNAME: musalauser
      SPRING_DATASOURCE_PASSWORD: 12345
      server_error_include-message: "always"

  front-server:
    build: ./frontend/
    links:
      - back-server
    ports:
      - 4200:4200
    depends_on:
      - back-server
    networks:
      - frontend

networks:
  backend:
  frontend:
